# Generated by Django 2.0 on 2018-07-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='selling_price',
            new_name='price',
        ),
    ]
