# Generated by Django 2.0 on 2018-07-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='cost_price',
        ),
    ]
