# Generated by Django 2.0 on 2018-07-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20180713_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_applies',
            field=models.BooleanField(default=True),
        ),
    ]
