# Generated by Django 2.0 on 2018-07-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180713_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='cost_price',
        ),
    ]
