# Generated by Django 2.0 on 2018-07-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180714_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=7),
            preserve_default=False,
        ),
    ]
