# Generated by Django 2.0 on 2018-07-15 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_purchase_selling_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['timestamp']},
        ),
    ]
